# Generated by Django 4.2.24 on 2025-10-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkred',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
